# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csample.proto\x12\x0enanoswap.proto\">\n\x07\x45xample\x12\"\n\x04type\x18\x01 \x01(\x0e\x32\x14.nanoswap.proto.Type\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t*\x1a\n\x04Type\x12\x08\n\x04\x46IZZ\x10\x00\x12\x08\n\x04\x42UZZ\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sample_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TYPE._serialized_start=96
  _TYPE._serialized_end=122
  _EXAMPLE._serialized_start=32
  _EXAMPLE._serialized_end=94
# @@protoc_insertion_point(module_scope)
